import Head from 'next/head'
import Fade from 'react-reveal/Fade';


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Fade left>
        <h1>Teste</h1>
      </Fade>
      

    </>
  )
}
